export const demoAccount = [
  { id: "002", username: "anto", password: "anto", role: "sales" },
  { id: "001", username: "kantor", password: "kantor", role: "sales" },
  { id: "004", username: "zainudin", password: "zainudin", role: "sales" },
  { id: "007", username: "aldi", password: "aldi", role: "sales" },
  { id: "006", username: "achun", password: "achun", role: "sales" },
  { id: "009", username: "joni", password: "joni", role: "sales" },
  { id: "005", username: "charles", password: "charles", role: "sales" },
  { id: "010", username: "ferel", password: "ferel", role: "sales" },
  { id: "010", username: "hendi", password: "hendi", role: "sales" },
  { id: "011", username: "arie", password: "arie", role: "sales" },
  {
    id: "012",
    username: "supervisor",
    password: "supervisor",
    role: "supervisor",
  },
  { id: "013", username: "agus", password: "agus", role: "sales" },
  { id: "014", username: "tomi", password: "tomi", role: "sales" },
  { id: "015", username: "herman", password: "herman", role: "sales" },
  { id: "016", username: "amin", password: "amin", role: "sales" },
  { id: "017", username: "hendra", password: "hendra", role: "sales" },
  { id: "018", username: "iwan", password: "iwan", role: "sales" },
  { id: "003", username: "kenny", password: "kenny", role: "sales" },
  { id: "019", username: "celvin", password: "celvin", role: "sales" },
];
