const items = [
  {
    name: "Notebook",
    price: 15000,
    stock: 100,
    description: "A simple 80-page notebook for daily use.",
    label: "Notebook",
    value: "notebook",
  },
  {
    name: "Ballpoint Pen",
    price: 10000,
    stock: 50,
    description: "A smooth-writing ballpoint pen.",
    label: "Ballpoint Pen",
    value: "ballpoint-pen",
  },
  {
    name: "Pencil",
    price: 5000,
    stock: 200,
    description: "A classic wooden pencil.",
    label: "Pencil",
    value: "pencil",
  },
  {
    name: "Eraser",
    price: 3000,
    stock: 75,
    description: "A durable rubber eraser.",
    label: "Eraser",
    value: "eraser",
  },
  {
    name: "Ruler",
    price: 7000,
    stock: 150,
    description: "A 30 cm transparent ruler.",
    label: "Ruler",
    value: "ruler",
  },
  {
    name: "Marker",
    price: 25000,
    stock: 30,
    description: "A black permanent marker.",
    label: "Marker",
    value: "marker",
  },
  {
    name: "Highlighter",
    price: 12000,
    stock: 300,
    description: "A yellow fluorescent highlighter.",
    label: "Highlighter",
    value: "highlighter",
  },
  {
    name: "Glue Stick",
    price: 20000,
    stock: 20,
    description: "A 15g glue stick.",
    label: "Glue Stick",
    value: "glue-stick",
  },
  {
    name: "Scissors",
    price: 18000,
    stock: 60,
    description: "A pair of medium-sized scissors.",
    label: "Scissors",
    value: "scissors",
  },
  {
    name: "Stapler",
    price: 25000,
    stock: 120,
    description: "A small stapler with 500 staples.",
    label: "Stapler",
    value: "stapler",
  },
  {
    name: "Paper Clips (50 pcs)",
    price: 10000,
    stock: 90,
    description: "A pack of 50 colorful paper clips.",
    label: "Paper Clips (50 pcs)",
    value: "paper-clips",
  },
  {
    name: "Correction Tape",
    price: 15000,
    stock: 250,
    description: "A compact correction tape.",
    label: "Correction Tape",
    value: "correction-tape",
  },
  {
    name: "Binder",
    price: 30000,
    stock: 40,
    description: "A durable A4 binder.",
    label: "Binder",
    value: "binder",
  },
  {
    name: "Sticky Notes",
    price: 20000,
    stock: 80,
    description: "A 100-sheet pad of sticky notes.",
    label: "Sticky Notes",
    value: "sticky-notes",
  },
  {
    name: "Sketchbook",
    price: 40000,
    stock: 350,
    description: "A 50-page A4 sketchbook.",
    label: "Sketchbook",
    value: "sketchbook",
  },
  {
    name: "Drawing Pencil Set",
    price: 75000,
    stock: 25,
    description: "A set of 12 drawing pencils.",
    label: "Drawing Pencil Set",
    value: "drawing-pencil-set",
  },
  {
    name: "Paint Brushes",
    price: 60000,
    stock: 55,
    description: "A set of 5 paint brushes.",
    label: "Paint Brushes",
    value: "paint-brushes",
  },
  {
    name: "Watercolor Paints",
    price: 85000,
    stock: 130,
    description: "A set of 12 watercolor paints.",
    label: "Watercolor Paints",
    value: "watercolor-paints",
  },
  {
    name: "Canvas Board",
    price: 90000,
    stock: 45,
    description: "A 30x40 cm canvas board.",
    label: "Canvas Board",
    value: "canvas-board",
  },
  {
    name: "Oil Pastels",
    price: 70000,
    stock: 220,
    description: "A set of 24 oil pastels.",
    label: "Oil Pastels",
    value: "oil-pastels",
  },
];

export default items;
